name: Keep Render Awake

on:
  schedule:
    - cron: '*/5 * * * *'   # 每 5 分钟运行一次
  workflow_dispatch:        # 允许手动触发

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render
        run: |
          curl -I https://jhm-new.onrender.com/ping
